logging.level.org.springframework.data.r2dbc=WARN
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=WARN
#logging.level.org.springframework.data=DEBUG
spring.mvc.log-request-details=true
spring.h2.console.enabled=true
spring.threads.virtual.enabled=true
spring.main.web-application-type=reactive

#datasource config
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:./schema.sql'
spring.datasource.jdbc-url=${spring.datasource.url}
spring.datasource.username=sa
spring.datasource.password=

spring.datasource.hikari.maximumPoolSize=100
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
#logging.level.org.hibernate.sql=debug

server.port=8081

#application parameters
remote.service.url=http://localhost:8081

#RSocket over WebSocket
spring.rsocket.server.transport=websocket
spring.rsocket.server.mapping-path=/rsocket

#Spring-ai properties
spring.ai.openai.api-key=${OPENAI_API_KEY:dummy-key}
spring.ai.openai.chat.options.model=gpt-5-chat-latest
spring.ai.openai.chat.options.temperature=0.0
spring.ai.openai.embedding.options.model=text-embedding-3-small
#spring.ai.ollama.chat.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=mistral
#spring.ai.ollama.chat.options.temperature=0.0

spring.ai.openai.chat.options.log-requests=true

