CREATE TABLE IF NOT EXISTS STOCKS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(255) NOT NULL,
    price DOUBLE NOT NULL,
    CONSTRAINT uk_stocks_symbol UNIQUE (symbol)
);

CREATE TABLE IF NOT EXISTS STOCK_EVENTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(10) NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    price DOUBLE NOT NULL
);

